# Makefile for crypto kernel module
obj-m += crypto_driver.o

KDIR := /lib/modules/$(shell uname -r)/build
PWD := $(shell pwd)

all:
	$(MAKE) -C $(KDIR) M=$(PWD) modules

clean:
	$(MAKE) -C $(KDIR) M=$(PWD) clean

install:
	sudo insmod crypto_driver.ko

uninstall:
	sudo rmmod crypto_driver

reload: uninstall install

.PHONY: all clean install uninstall reload
